from pathlib import Path

p = Path("tests/test_bgp_malformed.rs")
text = p.read_text(encoding="utf-8")
old = '''#[test]\nfn test_unsupported_message_types_are_rejected_by_type_not_by_accident() {\n    for bad_type in [0u8, 5, 6, 200, 255] {\n        let mut frame = BGP_MARKER.to_vec();\n        frame.extend_from_slice(&19u16.to_be_bytes());\n        frame.push(bad_type);\n        let err = BgpPdu::parse(&frame).unwrap_err();\n        assert_eq!(err.code, BGP_ERR_MESSAGE_HEADER, "type {}", bad_type);\n        assert_eq!(err.subcode, 3, "type {}", bad_type); // Bad Message Type\n    }\n    // An OPEN whose declared length cannot hold the fixed part is caught too.\n    let mut frame = BGP_MARKER.to_vec();\n    frame.extend_from_slice(&20u16.to_be_bytes());\n    frame.push(BGP_MSG_OPEN);\n    frame.push(4);\n    assert!(BgpPdu::parse(&frame).is_err());\n}\n'''
new = '''#[test]\nfn test_unsupported_message_types_are_rejected_by_type_not_by_accident() {\n    // Type 5 is ROUTE-REFRESH (RFC 2918), so only genuinely undefined types\n    // belong in this negative-control sweep.\n    for bad_type in [0u8, 6, 200, 255] {\n        let mut frame = BGP_MARKER.to_vec();\n        frame.extend_from_slice(&19u16.to_be_bytes());\n        frame.push(bad_type);\n        let err = BgpPdu::parse(&frame).unwrap_err();\n        assert_eq!(err.code, BGP_ERR_MESSAGE_HEADER, "type {}", bad_type);\n        assert_eq!(err.subcode, 3, "type {}", bad_type); // Bad Message Type\n    }\n\n    // Type 5 is recognised, but its body has exactly the RFC 2918 four-byte\n    // AFI/reserved/SAFI shape. A header-only message is therefore a length error,\n    // not a Bad Message Type error.\n    let mut refresh = BGP_MARKER.to_vec();\n    refresh.extend_from_slice(&19u16.to_be_bytes());\n    refresh.push(crate::common::bgp_lab::BGP_MSG_ROUTE_REFRESH_FOR_TEST);\n    let err = BgpPdu::parse(&refresh).unwrap_err();\n    assert_eq!(err.code, BGP_ERR_MESSAGE_HEADER);\n    assert_eq!(err.subcode, 2); // Bad Message Length\n\n    // An OPEN whose declared length cannot hold the fixed part is caught too.\n    let mut frame = BGP_MARKER.to_vec();\n    frame.extend_from_slice(&20u16.to_be_bytes());\n    frame.push(BGP_MSG_OPEN);\n    frame.push(4);\n    assert!(BgpPdu::parse(&frame).is_err());\n}\n'''
# Avoid adding a helper constant to common: refer to the public constant directly.
new = new.replace("crate::common::bgp_lab::BGP_MSG_ROUTE_REFRESH_FOR_TEST", "toy_tcpip::bgp::BGP_MSG_ROUTE_REFRESH")
if old not in text:
    raise SystemExit("expected malformed-message test block not found")
p.write_text(text.replace(old, new, 1), encoding="utf-8")
