// src/evpn_ssm_source_active.rs
//
// EVPN Source-Specific Multicast (SSM) Source Active (SA) Route Synchronization Engine
// References:
// - RFC 9251 Section 9: EVPN Source-Specific Multicast Source Active (SA) Signaling
// - RFC 7432: BGP MPLS-Based Ethernet VPN
// - RFC 8584: Multi-Homed EVPN Multicast Framework

use crate::ipv4::Ipv4Address;

pub const DEFAULT_SOURCE_INACTIVITY_TIMEOUT_SECS: u64 = 180;

/// BGP EVPN Source Active (SA) Route Representation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EvpnSourceActiveRoute {
    pub vni: u32,
    pub esi: [u8; 10],
    pub source_ip: Ipv4Address,
    pub group_ip: Ipv4Address,
    pub originator_router_ip: Ipv4Address,
}

/// Action generated by Source Active state machine.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SourceActiveVerdict {
    AdvertiseSourceActive {
        route: EvpnSourceActiveRoute,
    },
    SourceRefreshed {
        vni: u32,
        source_ip: Ipv4Address,
        group_ip: Ipv4Address,
        last_seen_secs: u64,
    },
    WithdrawSourceActive {
        route: EvpnSourceActiveRoute,
        reason: String,
    },
    ActiveSourceLocated {
        originator_router_ip: Ipv4Address,
        esi: [u8; 10],
        uptime_secs: u64,
    },
    SourceNotFound,
}

/// Managed active source record.
#[derive(Debug, Clone)]
pub struct ActiveSourceRecord {
    pub vni: u32,
    pub esi: [u8; 10],
    pub source_ip: Ipv4Address,
    pub group_ip: Ipv4Address,
    pub originator_router_ip: Ipv4Address,
    pub first_seen_secs: u64,
    pub last_seen_secs: u64,
    pub packet_count: u64,
    pub is_advertised: bool,
}

/// EVPN SSM Source Active (SA) Route Synchronization Engine.
#[derive(Debug, Clone)]
pub struct EvpnSourceActiveEngine {
    pub local_router_ip: Ipv4Address,
    pub source_inactivity_timeout_secs: u64,
    pub active_sources: Vec<ActiveSourceRecord>,
    pub total_sources_discovered: u64,
    pub total_sa_routes_advertised: u64,
    pub total_sa_routes_withdrawn: u64,
    pub total_traffic_refreshes: u64,
}

impl EvpnSourceActiveEngine {
    pub fn new(local_router_ip: Ipv4Address, source_inactivity_timeout_secs: u64) -> Self {
        Self {
            local_router_ip,
            source_inactivity_timeout_secs: if source_inactivity_timeout_secs == 0 {
                DEFAULT_SOURCE_INACTIVITY_TIMEOUT_SECS
            } else {
                source_inactivity_timeout_secs
            },
            active_sources: Vec::new(),
            total_sources_discovered: 0,
            total_sa_routes_advertised: 0,
            total_sa_routes_withdrawn: 0,
            total_traffic_refreshes: 0,
        }
    }

    /// Record ingress multicast traffic for channel (S, G) on an Ethernet Segment.
    pub fn record_source_traffic(
        &mut self,
        vni: u32,
        esi: [u8; 10],
        source_ip: Ipv4Address,
        group_ip: Ipv4Address,
        current_time_secs: u64,
    ) -> SourceActiveVerdict {
        if let Some(src) = self
            .active_sources
            .iter_mut()
            .find(|s| s.vni == vni && s.source_ip == source_ip && s.group_ip == group_ip)
        {
            src.last_seen_secs = current_time_secs;
            src.packet_count += 1;
            self.total_traffic_refreshes += 1;
            return SourceActiveVerdict::SourceRefreshed {
                vni,
                source_ip,
                group_ip,
                last_seen_secs: current_time_secs,
            };
        }

        // New active source detected
        let route = EvpnSourceActiveRoute {
            vni,
            esi,
            source_ip,
            group_ip,
            originator_router_ip: self.local_router_ip,
        };

        self.active_sources.push(ActiveSourceRecord {
            vni,
            esi,
            source_ip,
            group_ip,
            originator_router_ip: self.local_router_ip,
            first_seen_secs: current_time_secs,
            last_seen_secs: current_time_secs,
            packet_count: 1,
            is_advertised: true,
        });

        self.total_sources_discovered += 1;
        self.total_sa_routes_advertised += 1;

        SourceActiveVerdict::AdvertiseSourceActive { route }
    }

    /// Ingest a remote PE's Source Active route announcement.
    pub fn learn_remote_sa_route(&mut self, route: EvpnSourceActiveRoute, current_time_secs: u64) {
        if let Some(src) = self.active_sources.iter_mut().find(|s| {
            s.vni == route.vni
                && s.source_ip == route.source_ip
                && s.group_ip == route.group_ip
                && s.originator_router_ip == route.originator_router_ip
        }) {
            src.last_seen_secs = current_time_secs;
            src.packet_count += 1;
        } else {
            self.active_sources.push(ActiveSourceRecord {
                vni: route.vni,
                esi: route.esi,
                source_ip: route.source_ip,
                group_ip: route.group_ip,
                originator_router_ip: route.originator_router_ip,
                first_seen_secs: current_time_secs,
                last_seen_secs: current_time_secs,
                packet_count: 0,
                is_advertised: false, // Learned from remote PE
            });
            self.total_sources_discovered += 1;
        }
    }

    /// Check for inactive sources exceeding timeout and generate withdrawal routes.
    pub fn check_aging(&mut self, current_time_secs: u64) -> Vec<SourceActiveVerdict> {
        let mut withdrawals = Vec::new();
        let timeout = self.source_inactivity_timeout_secs;

        let mut remaining = Vec::new();
        for src in self.active_sources.drain(..) {
            if current_time_secs.saturating_sub(src.last_seen_secs) > timeout {
                if src.is_advertised {
                    self.total_sa_routes_withdrawn += 1;
                    withdrawals.push(SourceActiveVerdict::WithdrawSourceActive {
                        route: EvpnSourceActiveRoute {
                            vni: src.vni,
                            esi: src.esi,
                            source_ip: src.source_ip,
                            group_ip: src.group_ip,
                            originator_router_ip: src.originator_router_ip,
                        },
                        reason: format!(
                            "Source inactive for {}s (threshold: {}s)",
                            current_time_secs.saturating_sub(src.last_seen_secs),
                            timeout
                        ),
                    });
                }
            } else {
                remaining.push(src);
            }
        }
        self.active_sources = remaining;
        withdrawals
    }

    /// Query the active location and uptime of a multicast source.
    pub fn query_source_location(
        &self,
        vni: u32,
        source_ip: Ipv4Address,
        group_ip: Ipv4Address,
        current_time_secs: u64,
    ) -> SourceActiveVerdict {
        if let Some(src) = self
            .active_sources
            .iter()
            .find(|s| s.vni == vni && s.source_ip == source_ip && s.group_ip == group_ip)
        {
            SourceActiveVerdict::ActiveSourceLocated {
                originator_router_ip: src.originator_router_ip,
                esi: src.esi,
                uptime_secs: current_time_secs.saturating_sub(src.first_seen_secs),
            }
        } else {
            SourceActiveVerdict::SourceNotFound
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_evpn_source_active_discovery_and_aging() {
        let local_pe = Ipv4Address::new(10, 0, 0, 1);
        let mut engine = EvpnSourceActiveEngine::new(local_pe, 60);

        let esi = [0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99];
        let src_ip = Ipv4Address::new(192, 168, 100, 50);
        let grp_ip = Ipv4Address::new(232, 1, 1, 1);

        // 1. First packet from source -> SA Route Advertisement generated
        let v1 = engine.record_source_traffic(100, esi, src_ip, grp_ip, 1000);
        assert_eq!(
            v1,
            SourceActiveVerdict::AdvertiseSourceActive {
                route: EvpnSourceActiveRoute {
                    vni: 100,
                    esi,
                    source_ip: src_ip,
                    group_ip: grp_ip,
                    originator_router_ip: local_pe,
                }
            }
        );

        // 2. Query location -> located on local PE
        let loc = engine.query_source_location(100, src_ip, grp_ip, 1020);
        assert_eq!(
            loc,
            SourceActiveVerdict::ActiveSourceLocated {
                originator_router_ip: local_pe,
                esi,
                uptime_secs: 20,
            }
        );

        // 3. Keepalive at t = 1040
        let v2 = engine.record_source_traffic(100, esi, src_ip, grp_ip, 1040);
        assert_eq!(
            v2,
            SourceActiveVerdict::SourceRefreshed {
                vni: 100,
                source_ip: src_ip,
                group_ip: grp_ip,
                last_seen_secs: 1040,
            }
        );

        // 4. At t = 1090, 50s passed <= 60s -> no aging withdrawal
        let w1 = engine.check_aging(1090);
        assert!(w1.is_empty());

        // 5. At t = 1110, 70s passed > 60s -> SA Route Withdrawal generated
        let w2 = engine.check_aging(1110);
        assert_eq!(w2.len(), 1);
        match &w2[0] {
            SourceActiveVerdict::WithdrawSourceActive { route, .. } => {
                assert_eq!(route.source_ip, src_ip);
                assert_eq!(route.group_ip, grp_ip);
            }
            _ => panic!("Expected WithdrawSourceActive"),
        }

        assert_eq!(engine.total_sa_routes_advertised, 1);
        assert_eq!(engine.total_sa_routes_withdrawn, 1);
    }
}
