// =============================================================================
// EVPN Layer 2 Multicast IGMP/MLD Snooping Querier Election Engine
// =============================================================================
//
// In EVPN VXLAN datacenter fabrics (RFC 7432, RFC 9251, RFC 4541), in the absence
// of an external multicast router on a bridge domain, one of the leaf PEs attached
// to the Ethernet Segment must serve as the active IGMP/MLD Snooping Querier to
// generate periodic General Queries and solicit membership reports.
//
// According to RFC 2236 Section 3 / RFC 3376 Section 6.6.2:
//   - The switch/PE with the lowest numerical IP address is elected as Active Querier.
//   - Non-Querier switches arm an Other-Querier-Present timer (2 * Query Interval + Max Resp / 2).
//   - If no queries are received before the timer expires, the Non-Querier transitions back
//     to Active Querier (Failover).
//
// Pure safe Rust, zero external dependencies.

use crate::ipv4::Ipv4Address;

/// Querier operational role.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum QuerierRole {
    ActiveQuerier,
    NonQuerier,
}

/// State tracking a single EVPN VNI bridge domain querier instance.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VniQuerierInstance {
    pub vni: u32,
    pub local_ip: Ipv4Address,
    pub active_querier_ip: Ipv4Address,
    pub role: QuerierRole,
    pub startup_queries_left: u32,
    pub last_query_sent_s: u64,
    pub other_querier_expiry_s: u64,
    pub total_queries_sent: u64,
    pub total_queries_received: u64,
    pub total_failovers: u64,
}

/// Decision verdict returned on query processing or timer tick.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum QuerierVerdict {
    /// Local node elected as Active Querier.
    BecameActiveQuerier {
        vni: u32,
        local_ip: Ipv4Address,
        reason: &'static str,
    },
    /// A lower IP peer is recognized as the Active Querier (local node becomes Non-Querier).
    ElectedNonQuerier {
        vni: u32,
        active_querier_ip: Ipv4Address,
        other_querier_expiry_s: u64,
    },
    /// General query generated by local Active Querier.
    QueryDispatched {
        vni: u32,
        querier_ip: Ipv4Address,
        is_startup: bool,
    },
    /// Other querier timed out; local node failed over to become Active Querier.
    FailoverToActiveQuerier { vni: u32, local_ip: Ipv4Address },
    /// VNI instance was not found.
    VniNotFound { vni: u32 },
}

/// Engine managing EVPN IGMP Querier Election and Timers across VNIs.
pub struct EvpnIgmpQuerierElectionEngine {
    pub local_ip: Ipv4Address,
    pub query_interval_s: u64,
    pub query_response_interval_s: u64,
    pub other_querier_present_timeout_s: u64,
    pub startup_query_count: u32,
    pub instances: Vec<VniQuerierInstance>,
}

impl EvpnIgmpQuerierElectionEngine {
    pub fn new(
        local_ip: Ipv4Address,
        query_interval_s: u64,
        query_response_interval_s: u64,
        startup_query_count: u32,
    ) -> Self {
        let other_querier_present_timeout_s =
            (2 * query_interval_s) + (query_response_interval_s / 2).max(1);
        Self {
            local_ip,
            query_interval_s,
            query_response_interval_s,
            other_querier_present_timeout_s,
            startup_query_count,
            instances: Vec::new(),
        }
    }

    /// Registers a bridge domain VNI and initializes it in Active Querier state.
    pub fn register_vni(&mut self, vni: u32, current_time_s: u64) {
        if !self.instances.iter().any(|i| i.vni == vni) {
            self.instances.push(VniQuerierInstance {
                vni,
                local_ip: self.local_ip,
                active_querier_ip: self.local_ip,
                role: QuerierRole::ActiveQuerier,
                startup_queries_left: self.startup_query_count,
                last_query_sent_s: current_time_s,
                other_querier_expiry_s: 0,
                total_queries_sent: 0,
                total_queries_received: 0,
                total_failovers: 0,
            });
        }
    }

    /// Processes an incoming IGMP General Query from a peer PE on the VNI.
    pub fn process_rx_query(
        &mut self,
        vni: u32,
        peer_ip: Ipv4Address,
        current_time_s: u64,
    ) -> QuerierVerdict {
        if let Some(inst) = self.instances.iter_mut().find(|i| i.vni == vni) {
            inst.total_queries_received += 1;
            // Lowest IP address wins querier election (RFC 2236)
            if peer_ip.0 < self.local_ip.0 {
                let expiry = current_time_s + self.other_querier_present_timeout_s;
                inst.active_querier_ip = peer_ip;
                inst.role = QuerierRole::NonQuerier;
                inst.other_querier_expiry_s = expiry;
                QuerierVerdict::ElectedNonQuerier {
                    vni,
                    active_querier_ip: peer_ip,
                    other_querier_expiry_s: expiry,
                }
            } else {
                // Peer has a higher IP: we remain the Active Querier
                QuerierVerdict::BecameActiveQuerier {
                    vni,
                    local_ip: self.local_ip,
                    reason: "Local node IP is lower than peer querier IP.",
                }
            }
        } else {
            QuerierVerdict::VniNotFound { vni }
        }
    }

    /// Periodic timer tick to dispatch periodic queries and detect other querier failover.
    pub fn tick(&mut self, current_time_s: u64) -> Vec<QuerierVerdict> {
        let mut verdicts = Vec::new();
        for inst in &mut self.instances {
            match inst.role {
                QuerierRole::ActiveQuerier => {
                    let interval = if inst.startup_queries_left > 0 {
                        (self.query_interval_s / 4).max(1)
                    } else {
                        self.query_interval_s
                    };

                    if current_time_s >= inst.last_query_sent_s + interval {
                        inst.last_query_sent_s = current_time_s;
                        inst.total_queries_sent += 1;
                        let is_startup = inst.startup_queries_left > 0;
                        if is_startup {
                            inst.startup_queries_left -= 1;
                        }
                        verdicts.push(QuerierVerdict::QueryDispatched {
                            vni: inst.vni,
                            querier_ip: inst.local_ip,
                            is_startup,
                        });
                    }
                }
                QuerierRole::NonQuerier => {
                    if current_time_s >= inst.other_querier_expiry_s {
                        // Other querier failed to refresh -> failover to ActiveQuerier
                        inst.role = QuerierRole::ActiveQuerier;
                        inst.active_querier_ip = inst.local_ip;
                        inst.startup_queries_left = self.startup_query_count;
                        inst.last_query_sent_s = current_time_s;
                        inst.total_failovers += 1;
                        inst.total_queries_sent += 1;

                        verdicts.push(QuerierVerdict::FailoverToActiveQuerier {
                            vni: inst.vni,
                            local_ip: inst.local_ip,
                        });
                    }
                }
            }
        }
        verdicts
    }

    /// Resets all instances in the engine.
    pub fn reset(&mut self) {
        self.instances.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_querier_election_lifecycle() {
        let local_ip = Ipv4Address::new(10, 0, 0, 2);
        let mut engine = EvpnIgmpQuerierElectionEngine::new(local_ip, 120, 10, 2);
        engine.register_vni(100, 1000);

        assert_eq!(engine.instances[0].role, QuerierRole::ActiveQuerier);

        // Receive query from higher IP (10.0.0.3) -> should remain ActiveQuerier
        let v_high = engine.process_rx_query(100, Ipv4Address::new(10, 0, 0, 3), 1001);
        assert!(matches!(v_high, QuerierVerdict::BecameActiveQuerier { .. }));
        assert_eq!(engine.instances[0].role, QuerierRole::ActiveQuerier);

        // Receive query from lower IP (10.0.0.1) -> becomes NonQuerier
        let v_low = engine.process_rx_query(100, Ipv4Address::new(10, 0, 0, 1), 1002);
        match v_low {
            QuerierVerdict::ElectedNonQuerier {
                active_querier_ip, ..
            } => {
                assert_eq!(active_querier_ip, Ipv4Address::new(10, 0, 0, 1));
            }
            _ => panic!("Expected ElectedNonQuerier"),
        }
        assert_eq!(engine.instances[0].role, QuerierRole::NonQuerier);

        // Advance clock past other querier timeout (1002 + 245 = 1247)
        let v_failover = engine.tick(1300);
        assert_eq!(v_failover.len(), 1);
        assert_eq!(
            v_failover[0],
            QuerierVerdict::FailoverToActiveQuerier { vni: 100, local_ip }
        );
        assert_eq!(engine.instances[0].role, QuerierRole::ActiveQuerier);
    }
}
