//! PTP Telecom Profile Boundary Clock (T-BC - ITU-T G.8275.1 / G.8273.2).
//!
//! Implements the ITU-T G.8275.1 Alternate Best Master Clock Algorithm (BMCA),
//! local priority arbitration (localPriority 1..255), Steps-Removed override,
//! multi-port Boundary Clock state machine (Master, Slave, Passive), and phase error
//! accumulation filtering for 5G fronthaul and packet-based phase/time synchronization.

use std::collections::HashMap;

/// Telecom Profile Clock Port Role / State.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TelecomPortState {
    Master,
    Slave,
    Passive,
    Disabled,
}

/// T-BC Operational Synchronization State (ITU-T G.8273.2 Section 7.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TelecomSyncState {
    FreeRun,
    Locked,
    HoldoverWithinSpec,
    HoldoverOutOfSpec,
}

/// G.8275.1 Telecom Profile Clock Quality Attributes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct TelecomClockQuality {
    pub clock_class: u8, // 6 = PRTC (Primary Reference Time Clock), 7, 135, 140, 248
    pub clock_accuracy: u8, // 0x20 = Within 25ns, 0x21 = Within 100ns
    pub offset_scaled_log_variance: u16,
}

/// Downstream Announce Dataset generated by T-BC Master ports.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DownstreamAnnounceDataset {
    pub grandmaster_clock_quality: TelecomClockQuality,
    pub steps_removed: u16,
    pub local_priority: u8,
    pub time_source: u8, // 0x20 = PTP, 0x90 = Internal Oscillator
}

/// Port configuration and received grandmaster Announce dataset.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TelecomPortConfig {
    pub port_id: u32,
    pub local_priority: u8, // 1..255 (lower = preferred in G.8275.1)
    pub not_slave: bool,    // If true, port can only be Master or Passive
    pub rx_clock_quality: Option<TelecomClockQuality>,
    pub rx_steps_removed: u16,
    pub rx_grandmaster_priority: u8,
    pub ingress_latency_ns: i64,
    pub egress_latency_ns: i64,
    pub asymmetry_compensation_ns: i64,
}

/// Telecom Boundary Clock (T-BC) Protocol Engine (ITU-T G.8275.1 / G.8273.2).
#[derive(Debug, Clone)]
pub struct TelecomBoundaryClockEngine {
    pub ports: HashMap<u32, TelecomPortConfig>,
    pub port_states: HashMap<u32, TelecomPortState>,
    pub slave_port: Option<u32>,
    pub accumulated_phase_offset_ns: i64,
    pub bmca_cycles_run: usize,
    pub sync_state: TelecomSyncState,
    pub holdover_duration_secs: u64,
    pub max_holdover_within_spec_secs: u64,
    pub internal_oscillator_drift_ppb: f64,
    pub max_steps_removed: u16,
    pub slew_limit_ns_per_sec: i64,
}

impl Default for TelecomBoundaryClockEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl TelecomBoundaryClockEngine {
    pub fn new() -> Self {
        TelecomBoundaryClockEngine {
            ports: HashMap::new(),
            port_states: HashMap::new(),
            slave_port: None,
            accumulated_phase_offset_ns: 0,
            bmca_cycles_run: 0,
            sync_state: TelecomSyncState::FreeRun,
            holdover_duration_secs: 0,
            max_holdover_within_spec_secs: 14400, // 4 hours
            internal_oscillator_drift_ppb: 5.0,
            max_steps_removed: 20,
            slew_limit_ns_per_sec: 50, // 50 ns/s standard slew limit
        }
    }

    pub fn with_max_steps_removed(mut self, max: u16) -> Self {
        self.max_steps_removed = max;
        self
    }

    pub fn with_slew_limit(mut self, slew_limit: i64) -> Self {
        self.slew_limit_ns_per_sec = slew_limit;
        self
    }

    /// Configures a physical T-BC port.
    pub fn add_port(&mut self, port_id: u32, local_priority: u8, not_slave: bool) {
        self.ports.insert(
            port_id,
            TelecomPortConfig {
                port_id,
                local_priority,
                not_slave,
                rx_clock_quality: None,
                rx_steps_removed: 0,
                rx_grandmaster_priority: 128,
                ingress_latency_ns: 0,
                egress_latency_ns: 0,
                asymmetry_compensation_ns: 0,
            },
        );
        self.port_states.insert(port_id, TelecomPortState::Master);
    }

    /// Ingests received Announce timing data on a port.
    pub fn update_rx_announce(
        &mut self,
        port_id: u32,
        quality: TelecomClockQuality,
        steps_removed: u16,
        gm_priority: u8,
    ) {
        if let Some(port) = self.ports.get_mut(&port_id) {
            port.rx_clock_quality = Some(quality);
            port.rx_steps_removed = steps_removed;
            port.rx_grandmaster_priority = gm_priority;
        }
    }

    /// Runs ITU-T G.8275.1 Alternate BMCA across all configured Boundary Clock ports.
    pub fn run_alternate_bmca(&mut self) -> Option<u32> {
        self.bmca_cycles_run += 1;

        // Candidate ports eligible to become Slave:
        // (port_id, clock_class, local_priority, steps_removed)
        let mut best: Option<(u32, u8, u8, u16)> = None;

        for port in self.ports.values() {
            if port.not_slave || port.rx_steps_removed >= self.max_steps_removed {
                continue;
            }
            let quality = match port.rx_clock_quality {
                Some(q) => q,
                None => continue,
            };

            // ITU-T G.8275.1 BMCA Comparison:
            // 1. Clock Class (lower = superior)
            // 2. Local Priority (lower = preferred)
            // 3. Steps Removed (lower = shorter distance to GM)
            let cand = (
                port.port_id,
                quality.clock_class,
                port.local_priority,
                port.rx_steps_removed,
            );

            match best {
                None => best = Some(cand),
                Some((_, b_class, b_prio, b_steps)) => {
                    if cand.1 < b_class
                        || (cand.1 == b_class && cand.2 < b_prio)
                        || (cand.1 == b_class && cand.2 == b_prio && cand.3 < b_steps)
                    {
                        best = Some(cand);
                    }
                }
            }
        }

        if let Some((best_slave_port, _, _, _)) = best {
            self.slave_port = Some(best_slave_port);
            self.sync_state = TelecomSyncState::Locked;
            self.holdover_duration_secs = 0;
            for (pid, state) in self.port_states.iter_mut() {
                if *pid == best_slave_port {
                    *state = TelecomPortState::Slave;
                } else if self.ports.get(pid).map(|p| p.not_slave).unwrap_or(false) {
                    *state = TelecomPortState::Master;
                } else {
                    *state = TelecomPortState::Passive;
                }
            }
            Some(best_slave_port)
        } else {
            self.slave_port = None;
            if self.sync_state == TelecomSyncState::Locked {
                self.sync_state = TelecomSyncState::HoldoverWithinSpec;
            }
            for state in self.port_states.values_mut() {
                *state = TelecomPortState::Master;
            }
            None
        }
    }

    /// Filters and adjusts local phase offset error (in nanoseconds).
    pub fn adjust_phase_offset(&mut self, phase_error_ns: i64) -> i64 {
        // Apply damping filter
        let correction = phase_error_ns / 2;
        self.accumulated_phase_offset_ns += correction;
        correction
    }

    /// Detects whether an incoming phase error constitutes an abrupt phase step exceeding threshold.
    pub fn detect_phase_step(&self, phase_error_ns: i64, threshold_ns: i64) -> bool {
        phase_error_ns.abs() > threshold_ns
    }

    /// Smoothly adjusts the local clock phase toward target using slew-rate limiting (ns/s).
    ///
    /// Prevents sharp phase transients that cause downstream 5G O-RU / radio unit PLL dropouts.
    pub fn slew_adjust_phase(&mut self, target_phase_error_ns: i64, elapsed_secs: u64) -> i64 {
        let max_slew = (self.slew_limit_ns_per_sec * (elapsed_secs as i64)).abs();
        let adjustment = if target_phase_error_ns > max_slew {
            max_slew
        } else if target_phase_error_ns < -max_slew {
            -max_slew
        } else {
            target_phase_error_ns
        };

        self.accumulated_phase_offset_ns += adjustment;
        adjustment
    }

    /// Sets ingress and egress physical latency on a port and calculates delay asymmetry compensation (ITU-T G.8275.1 Section 6.2).
    pub fn set_port_asymmetry(&mut self, port_id: u32, ingress_ns: i64, egress_ns: i64) {
        if let Some(port) = self.ports.get_mut(&port_id) {
            port.ingress_latency_ns = ingress_ns;
            port.egress_latency_ns = egress_ns;
            // Delay asymmetry = (egress - ingress) / 2
            port.asymmetry_compensation_ns = (egress_ns - ingress_ns) / 2;
        }
    }

    /// Compensates measured mean path delay for known physical PHY/fiber asymmetry.
    pub fn compensate_measured_delay(&self, port_id: u32, raw_mean_delay_ns: i64) -> i64 {
        if let Some(port) = self.ports.get(&port_id) {
            raw_mean_delay_ns - port.asymmetry_compensation_ns
        } else {
            raw_mean_delay_ns
        }
    }

    /// Handles an Announce receipt timeout on a port (e.g. signal loss or link down).
    pub fn handle_announce_timeout(&mut self, port_id: u32) {
        if let Some(port) = self.ports.get_mut(&port_id) {
            port.rx_clock_quality = None;
            port.rx_steps_removed = 0;
        }

        if self.slave_port == Some(port_id) {
            self.slave_port = None;
            if self.sync_state == TelecomSyncState::Locked {
                self.sync_state = TelecomSyncState::HoldoverWithinSpec;
                self.holdover_duration_secs = 0;
            }
            // Transition other ports to Master
            for state in self.port_states.values_mut() {
                *state = TelecomPortState::Master;
            }
        }
    }

    /// Advances the holdover timer by `elapsed_secs`, accumulating phase drift and degrading clock class when budget expires.
    pub fn tick_holdover(&mut self, elapsed_secs: u64) {
        if self.sync_state == TelecomSyncState::HoldoverWithinSpec
            || self.sync_state == TelecomSyncState::HoldoverOutOfSpec
        {
            self.holdover_duration_secs += elapsed_secs;

            // Phase drift in nanoseconds = drift_ppb * elapsed_secs (ppb = ns/s)
            let drift_ns =
                (self.internal_oscillator_drift_ppb * (elapsed_secs as f64)).round() as i64;
            self.accumulated_phase_offset_ns += drift_ns;

            if self.holdover_duration_secs > self.max_holdover_within_spec_secs {
                self.sync_state = TelecomSyncState::HoldoverOutOfSpec;
            }
        }
    }

    /// Returns the active output clock quality advertised to downstream slaves (ITU-T G.8275.1).
    pub fn current_output_clock_quality(&self) -> TelecomClockQuality {
        match self.sync_state {
            TelecomSyncState::Locked => {
                if let Some(slave_pid) = self.slave_port {
                    if let Some(port) = self.ports.get(&slave_pid) {
                        if let Some(q) = port.rx_clock_quality {
                            return q;
                        }
                    }
                }
                TelecomClockQuality {
                    clock_class: 6,
                    clock_accuracy: 0x20,
                    offset_scaled_log_variance: 0x4E5D,
                }
            }
            TelecomSyncState::HoldoverWithinSpec => TelecomClockQuality {
                clock_class: 7,       // Holdover within specification (< 1.5us / G.8273.2)
                clock_accuracy: 0x21, // Within 100ns
                offset_scaled_log_variance: 0x4E5D,
            },
            TelecomSyncState::HoldoverOutOfSpec => TelecomClockQuality {
                clock_class: 140, // Holdover out of specification (Cat 1/2/3)
                clock_accuracy: 0x31,
                offset_scaled_log_variance: 0xFFFF,
            },
            TelecomSyncState::FreeRun => TelecomClockQuality {
                clock_class: 248, // Default free-running local oscillator
                clock_accuracy: 0xFE,
                offset_scaled_log_variance: 0xFFFF,
            },
        }
    }

    /// Generates downstream Announce metadata dataset on a designated Master port.
    pub fn generate_downstream_announce(&self, port_id: u32) -> Option<DownstreamAnnounceDataset> {
        let state = self.port_states.get(&port_id)?;
        if *state != TelecomPortState::Master {
            return None;
        }

        let port_cfg = self.ports.get(&port_id)?;
        let steps_removed = if let Some(slave_pid) = self.slave_port {
            self.ports
                .get(&slave_pid)
                .map(|p| p.rx_steps_removed.saturating_add(1))
                .unwrap_or(1)
        } else {
            0
        };

        let time_source = if self.sync_state == TelecomSyncState::Locked {
            0x20 // PTP
        } else {
            0x90 // Internal Oscillator
        };

        Some(DownstreamAnnounceDataset {
            grandmaster_clock_quality: self.current_output_clock_quality(),
            steps_removed,
            local_priority: port_cfg.local_priority,
            time_source,
        })
    }
}
