//! 3GPP TS 29.244 PFCP Advanced UPF Packet Processing Pipeline.
//!
//! Implements 5G User Plane Function (UPF) data-path processing driven by N4 PFCP rules:
//! - PDR: Packet classification via Source Interface, F-TEID, UE IP, and SDF filter.
//! - QER: QoS gate enforcement, token bucket rate policing (MBR/GBR), and QFI tagging.
//! - URR: Volume/time quota accounting and usage threshold reporting.
//! - BAR: CM-IDLE downlink packet buffering and Downlink Data Notification (DDN) emission.
//! - FAR: Forwarding action execution with GTP-U outer header creation or decapsulation.

use std::collections::HashMap;

use crate::ipv4::Ipv4Address;
use crate::pfcp_5g::{PFCP_APPLY_ACTION_BUFF, PFCP_APPLY_ACTION_DROP, PFCP_APPLY_ACTION_FORWARD};

/// Gate Status in QER.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GateStatus {
    Open,
    Closed,
}

/// Token Bucket Rate Policer for MBR/GBR enforcement.
#[derive(Debug, Clone)]
pub struct TokenBucketPolicer {
    pub rate_bytes_per_sec: u64,
    pub burst_capacity_bytes: u64,
    pub available_tokens: f64,
    pub last_update_ms: Option<u64>,
}

impl TokenBucketPolicer {
    pub fn new(rate_kbps: u32, burst_bytes: u64) -> Self {
        let rate_bytes_per_sec = (rate_kbps as u64) * 1000 / 8;
        Self {
            rate_bytes_per_sec,
            burst_capacity_bytes: burst_bytes,
            available_tokens: burst_bytes as f64,
            last_update_ms: None,
        }
    }

    pub fn consume(&mut self, bytes: u64, now_ms: u64) -> bool {
        let last = match self.last_update_ms {
            Some(t) => t,
            None => {
                self.last_update_ms = Some(now_ms);
                now_ms
            }
        };

        let elapsed_sec = (now_ms.saturating_sub(last) as f64) / 1000.0;
        self.last_update_ms = Some(now_ms);

        let added = elapsed_sec * (self.rate_bytes_per_sec as f64);
        self.available_tokens =
            (self.available_tokens + added).min(self.burst_capacity_bytes as f64);

        let required = bytes as f64;
        if self.available_tokens >= required {
            self.available_tokens -= required;
            true
        } else {
            false
        }
    }
}

/// 5G QoS Enforcement Rule (QER).
#[derive(Debug, Clone)]
pub struct UpfQer {
    pub qer_id: u16,
    pub gate_status_ul: GateStatus,
    pub gate_status_dl: GateStatus,
    pub mbr_ul_kbps: Option<u32>,
    pub mbr_dl_kbps: Option<u32>,
    pub qfi: u8,
    pub policer_ul: Option<TokenBucketPolicer>,
    pub policer_dl: Option<TokenBucketPolicer>,
}

impl UpfQer {
    pub fn new(qer_id: u16, qfi: u8) -> Self {
        Self {
            qer_id,
            gate_status_ul: GateStatus::Open,
            gate_status_dl: GateStatus::Open,
            mbr_ul_kbps: None,
            mbr_dl_kbps: None,
            qfi,
            policer_ul: None,
            policer_dl: None,
        }
    }

    pub fn set_mbr(&mut self, ul_kbps: Option<u32>, dl_kbps: Option<u32>, burst_bytes: u64) {
        self.mbr_ul_kbps = ul_kbps;
        self.mbr_dl_kbps = dl_kbps;
        self.policer_ul = ul_kbps.map(|r| TokenBucketPolicer::new(r, burst_bytes));
        self.policer_dl = dl_kbps.map(|r| TokenBucketPolicer::new(r, burst_bytes));
    }
}

/// Usage Report record generated by URR.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UsageReport {
    pub urr_id: u16,
    pub ul_bytes: u64,
    pub dl_bytes: u64,
    pub total_bytes: u64,
    pub ul_packets: u64,
    pub dl_packets: u64,
    pub trigger: &'static str,
}

/// 5G Usage Reporting Rule (URR).
#[derive(Debug, Clone)]
pub struct UpfUrr {
    pub urr_id: u16,
    pub volume_threshold_bytes: Option<u64>,
    pub consumed_ul_bytes: u64,
    pub consumed_dl_bytes: u64,
    pub consumed_ul_pkts: u64,
    pub consumed_dl_pkts: u64,
    pub threshold_reached: bool,
}

impl UpfUrr {
    pub fn new(urr_id: u16, volume_threshold_bytes: Option<u64>) -> Self {
        Self {
            urr_id,
            volume_threshold_bytes,
            consumed_ul_bytes: 0,
            consumed_dl_bytes: 0,
            consumed_ul_pkts: 0,
            consumed_dl_pkts: 0,
            threshold_reached: false,
        }
    }

    pub fn record_packet(&mut self, bytes: u64, is_uplink: bool) {
        if is_uplink {
            self.consumed_ul_bytes += bytes;
            self.consumed_ul_pkts += 1;
        } else {
            self.consumed_dl_bytes += bytes;
            self.consumed_dl_pkts += 1;
        }

        if let Some(thresh) = self.volume_threshold_bytes {
            if (self.consumed_ul_bytes + self.consumed_dl_bytes) >= thresh {
                self.threshold_reached = true;
            }
        }
    }

    pub fn generate_report(&mut self, trigger: &'static str) -> UsageReport {
        let report = UsageReport {
            urr_id: self.urr_id,
            ul_bytes: self.consumed_ul_bytes,
            dl_bytes: self.consumed_dl_bytes,
            total_bytes: self.consumed_ul_bytes + self.consumed_dl_bytes,
            ul_packets: self.consumed_ul_pkts,
            dl_packets: self.consumed_dl_pkts,
            trigger,
        };
        self.threshold_reached = false;
        report
    }
}

/// 5G Buffering Action Rule (BAR) for CM-IDLE Downlink Buffering.
#[derive(Debug, Clone)]
pub struct UpfBar {
    pub bar_id: u16,
    pub max_buffered_packets: usize,
    pub buffer: Vec<Vec<u8>>,
    pub ddn_sent: bool,
}

impl UpfBar {
    pub fn new(bar_id: u16, max_buffered_packets: usize) -> Self {
        Self {
            bar_id,
            max_buffered_packets,
            buffer: Vec::new(),
            ddn_sent: false,
        }
    }

    /// Buffers packet; returns true if this is the first packet triggering DDN.
    pub fn buffer_packet(&mut self, packet: Vec<u8>) -> bool {
        if self.buffer.len() < self.max_buffered_packets {
            self.buffer.push(packet);
        }
        if !self.ddn_sent {
            self.ddn_sent = true;
            true
        } else {
            false
        }
    }

    pub fn flush(&mut self) -> Vec<Vec<u8>> {
        self.ddn_sent = false;
        std::mem::take(&mut self.buffer)
    }
}

/// Advanced PDR for fast-path pipeline.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpfPdr {
    pub pdr_id: u16,
    pub precedence: u32,
    pub source_interface: u8,
    pub teid: Option<u32>,
    pub ue_ip: Option<Ipv4Address>,
    pub far_id: u16,
    pub qer_ids: Vec<u16>,
    pub urr_ids: Vec<u16>,
}

/// Advanced FAR for fast-path pipeline.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpfFar {
    pub far_id: u16,
    pub apply_action: u8,
    pub destination_interface: u8,
    pub outer_header_creation: Option<(u32, Ipv4Address)>, // (TEID, Target IP)
    pub bar_id: Option<u16>,
}

/// Complete UPF Session with full PDR/FAR/QER/URR/BAR rules.
#[derive(Debug, Clone)]
pub struct UpfSession {
    pub seid: u64,
    pub pdrs: HashMap<u16, UpfPdr>,
    pub fars: HashMap<u16, UpfFar>,
    pub qers: HashMap<u16, UpfQer>,
    pub urrs: HashMap<u16, UpfUrr>,
    pub bars: HashMap<u16, UpfBar>,
}

impl UpfSession {
    pub fn new(seid: u64) -> Self {
        Self {
            seid,
            pdrs: HashMap::new(),
            fars: HashMap::new(),
            qers: HashMap::new(),
            urrs: HashMap::new(),
            bars: HashMap::new(),
        }
    }
}

/// Result of processing an ingress packet through the UPF pipeline.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PacketProcessingResult {
    Forwarded {
        dst_ip: Ipv4Address,
        outer_header_teid: Option<u32>,
        qfi: u8,
        payload: Vec<u8>,
    },
    Buffered {
        bar_id: u16,
        ddn_triggered: bool,
    },
    Dropped {
        reason: &'static str,
    },
}

/// High-Performance 5G UPF Packet Processing Pipeline Engine.
#[derive(Debug, Default)]
pub struct UpfPipeline {
    pub sessions: HashMap<u64, UpfSession>,
    pub teid_index: HashMap<u32, u64>,
    pub ue_ip_index: HashMap<Ipv4Address, u64>,
}

impl UpfPipeline {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn add_session(&mut self, session: UpfSession) {
        for pdr in session.pdrs.values() {
            if let Some(teid) = pdr.teid {
                self.teid_index.insert(teid, session.seid);
            }
            if let Some(ue_ip) = pdr.ue_ip {
                self.ue_ip_index.insert(ue_ip, session.seid);
            }
        }
        self.sessions.insert(session.seid, session);
    }

    pub fn remove_session(&mut self, seid: u64) -> Option<UpfSession> {
        if let Some(session) = self.sessions.remove(&seid) {
            for pdr in session.pdrs.values() {
                if let Some(teid) = pdr.teid {
                    self.teid_index.remove(&teid);
                }
                if let Some(ue_ip) = pdr.ue_ip {
                    self.ue_ip_index.remove(&ue_ip);
                }
            }
            Some(session)
        } else {
            None
        }
    }

    /// Ingress packet processing through UPF pipeline.
    pub fn process_ingress_packet(
        &mut self,
        source_interface: u8,
        ingress_teid: Option<u32>,
        ue_ip: Option<Ipv4Address>,
        payload: &[u8],
        now_ms: u64,
    ) -> PacketProcessingResult {
        let is_uplink = source_interface == 0; // Access is uplink, Core is downlink

        // 1. Session lookup
        let seid = if let Some(teid) = ingress_teid {
            self.teid_index.get(&teid).copied()
        } else if let Some(ip) = ue_ip {
            self.ue_ip_index.get(&ip).copied()
        } else {
            None
        };

        let seid = match seid {
            Some(s) => s,
            None => {
                return PacketProcessingResult::Dropped {
                    reason: "No matching session found",
                };
            }
        };

        let session = match self.sessions.get_mut(&seid) {
            Some(s) => s,
            None => {
                return PacketProcessingResult::Dropped {
                    reason: "Session not active",
                };
            }
        };

        // 2. PDR Matching by Precedence (lowest number first)
        let mut matching_pdrs: Vec<&UpfPdr> = session
            .pdrs
            .values()
            .filter(|pdr| {
                if pdr.source_interface != source_interface {
                    return false;
                }
                if let Some(t) = ingress_teid {
                    if pdr.teid != Some(t) {
                        return false;
                    }
                }
                if let Some(ip) = ue_ip {
                    if pdr.ue_ip != Some(ip) {
                        return false;
                    }
                }
                true
            })
            .collect();

        matching_pdrs.sort_by_key(|pdr| pdr.precedence);
        let pdr = match matching_pdrs.first() {
            Some(p) => (*p).clone(),
            None => {
                return PacketProcessingResult::Dropped {
                    reason: "No matching PDR",
                };
            }
        };

        // 3. QER Evaluation
        let mut enforced_qfi = 1;
        for qer_id in &pdr.qer_ids {
            if let Some(qer) = session.qers.get_mut(qer_id) {
                enforced_qfi = qer.qfi;

                // Check Gate
                if is_uplink && qer.gate_status_ul == GateStatus::Closed {
                    return PacketProcessingResult::Dropped {
                        reason: "QER UL gate is closed",
                    };
                }
                if !is_uplink && qer.gate_status_dl == GateStatus::Closed {
                    return PacketProcessingResult::Dropped {
                        reason: "QER DL gate is closed",
                    };
                }

                // Check Policer
                let policer = if is_uplink {
                    &mut qer.policer_ul
                } else {
                    &mut qer.policer_dl
                };

                if let Some(p) = policer {
                    if !p.consume(payload.len() as u64, now_ms) {
                        return PacketProcessingResult::Dropped {
                            reason: "MBR policer rate exceeded",
                        };
                    }
                }
            }
        }

        // 4. URR Accounting
        for urr_id in &pdr.urr_ids {
            if let Some(urr) = session.urrs.get_mut(urr_id) {
                urr.record_packet(payload.len() as u64, is_uplink);
            }
        }

        // 5. FAR Evaluation
        let far = match session.fars.get(&pdr.far_id) {
            Some(f) => f.clone(),
            None => {
                return PacketProcessingResult::Dropped {
                    reason: "FAR not found",
                };
            }
        };

        if (far.apply_action & PFCP_APPLY_ACTION_DROP) != 0 {
            return PacketProcessingResult::Dropped {
                reason: "FAR action is DROP",
            };
        }

        if (far.apply_action & PFCP_APPLY_ACTION_BUFF) != 0 {
            if let Some(bar_id) = far.bar_id {
                if let Some(bar) = session.bars.get_mut(&bar_id) {
                    let ddn = bar.buffer_packet(payload.to_vec());
                    return PacketProcessingResult::Buffered {
                        bar_id,
                        ddn_triggered: ddn,
                    };
                }
            }
            return PacketProcessingResult::Dropped {
                reason: "BAR not configured for BUFF",
            };
        }

        if (far.apply_action & PFCP_APPLY_ACTION_FORWARD) != 0 {
            if let Some((outer_teid, target_ip)) = far.outer_header_creation {
                // Downlink forward with GTP-U encapsulation
                PacketProcessingResult::Forwarded {
                    dst_ip: target_ip,
                    outer_header_teid: Some(outer_teid),
                    qfi: enforced_qfi,
                    payload: payload.to_vec(),
                }
            } else {
                // Uplink forward to DN (decapsulated raw IP)
                let dst_ip = ue_ip.unwrap_or_else(|| Ipv4Address::new(0, 0, 0, 0));
                PacketProcessingResult::Forwarded {
                    dst_ip,
                    outer_header_teid: None,
                    qfi: enforced_qfi,
                    payload: payload.to_vec(),
                }
            }
        } else {
            PacketProcessingResult::Dropped {
                reason: "Unsupported FAR action",
            }
        }
    }

    /// Flushes buffered packets when UE transitions from CM-IDLE to CM-CONNECTED.
    pub fn flush_buffered_packets(
        &mut self,
        seid: u64,
        bar_id: u16,
    ) -> Vec<PacketProcessingResult> {
        let mut results = Vec::new();
        if let Some(session) = self.sessions.get_mut(&seid) {
            let packets = if let Some(bar) = session.bars.get_mut(&bar_id) {
                bar.flush()
            } else {
                Vec::new()
            };

            // Find DL forwarding FAR
            let dl_far = session
                .fars
                .values()
                .find(|f| {
                    (f.apply_action & PFCP_APPLY_ACTION_FORWARD) != 0
                        && f.outer_header_creation.is_some()
                })
                .cloned();

            if let Some(far) = dl_far {
                let (teid, target_ip) = far.outer_header_creation.unwrap();
                for pkt in packets {
                    results.push(PacketProcessingResult::Forwarded {
                        dst_ip: target_ip,
                        outer_header_teid: Some(teid),
                        qfi: 1,
                        payload: pkt,
                    });
                }
            }
        }
        results
    }

    /// Collects usage reports when thresholds are met or requested by SMF.
    pub fn collect_usage_reports(&mut self, seid: u64) -> Vec<UsageReport> {
        let mut reports = Vec::new();
        if let Some(session) = self.sessions.get_mut(&seid) {
            for urr in session.urrs.values_mut() {
                if urr.threshold_reached {
                    reports.push(urr.generate_report("VolumeThreshold"));
                }
            }
        }
        reports
    }
}
